version: "3.7"

services:

  nginx:
    image: nginx:1.19.5
    ports:
      - 80:80
    networks:
      - network
    volumes:
      - /home/kyh12kr/nginx.conf:/etc/nginx/nginx.conf
      - static:/data/static/
      - media:/data/media/
      - gis_log:/var/log/nginx/

  django:
    image: gis_4ba_django:5
    networks:
      - network
    volumes:
      - static:/home/gis_4ba_1/staticfiles/
      - media:/home/gis_4ba_1/media/
    secrets:
      - DJANGO_SECRET_KEY
      - MARIADB_USER
      - MARIADB_PASSWORD


  mariadb:
    image: mariadb:10.5
    networks:
      - network
    volumes:
    - mariadb:/var/lib/mysql
    secrets:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_USER
      - MARIADB_PASSWORD
    environment:
      MARIADB_DATABASE: django
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/MARIADB_ROOT_PASSWORD
      MARIADB_USER_FILE: /run/secrets/MARIADB_USER
      MARIADB_PASSWORD_FILE: /run/secrets/MARIADB_PASSWORD


networks:
  network:

volumes:
  static:
  media:
  mariadb:
  gis_log:

secrets:
  DJANGO_SECRET_KEY:
    external: true
  MARIADB_ROOT_PASSWORD:
    external: true
  MARIADB_USER:
    external: true
  MARIADB_PASSWORD:
    external: true
